name: Metrics
on:
  schedule:
    - cron: "0 0 * * 1"
  push: {branches: ["master"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: jx2lee
          template: terminal
          base: header, activity, community, repositories
          config_animations: yes
          config_timezone: Asia/Seoul
          plugin_isocalendar: no
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, javascript, css, xslt, mustache, vim script, stylus, ejs, nunjucks, jupyter notebook, scss, jinja
          plugin_lines: yes
