name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  push: {branches: ["master"]}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jx2lee
          svg_out_path: dist/github-contribution-grid-snake.svg
      - run: git status
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: $
